// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/central-university-dev/go-Matthew11K/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// LinkRepository is an autogenerated mock type for the LinkRepository type
type LinkRepository struct {
	mock.Mock
}

type LinkRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *LinkRepository) EXPECT() *LinkRepository_Expecter {
	return &LinkRepository_Expecter{mock: &_m.Mock}
}

// AddChatLink provides a mock function with given fields: ctx, chatID, linkID
func (_m *LinkRepository) AddChatLink(ctx context.Context, chatID int64, linkID int64) error {
	ret := _m.Called(ctx, chatID, linkID)

	if len(ret) == 0 {
		panic("no return value specified for AddChatLink")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, chatID, linkID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepository_AddChatLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddChatLink'
type LinkRepository_AddChatLink_Call struct {
	*mock.Call
}

// AddChatLink is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
//   - linkID int64
func (_e *LinkRepository_Expecter) AddChatLink(ctx interface{}, chatID interface{}, linkID interface{}) *LinkRepository_AddChatLink_Call {
	return &LinkRepository_AddChatLink_Call{Call: _e.mock.On("AddChatLink", ctx, chatID, linkID)}
}

func (_c *LinkRepository_AddChatLink_Call) Run(run func(ctx context.Context, chatID int64, linkID int64)) *LinkRepository_AddChatLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].(int64))
	})
	return _c
}

func (_c *LinkRepository_AddChatLink_Call) Return(_a0 error) *LinkRepository_AddChatLink_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepository_AddChatLink_Call) RunAndReturn(run func(context.Context, int64, int64) error) *LinkRepository_AddChatLink_Call {
	_c.Call.Return(run)
	return _c
}

// Count provides a mock function with given fields: ctx
func (_m *LinkRepository) Count(ctx context.Context) (int, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Count")
	}

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepository_Count_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Count'
type LinkRepository_Count_Call struct {
	*mock.Call
}

// Count is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LinkRepository_Expecter) Count(ctx interface{}) *LinkRepository_Count_Call {
	return &LinkRepository_Count_Call{Call: _e.mock.On("Count", ctx)}
}

func (_c *LinkRepository_Count_Call) Run(run func(ctx context.Context)) *LinkRepository_Count_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LinkRepository_Count_Call) Return(_a0 int, _a1 error) *LinkRepository_Count_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepository_Count_Call) RunAndReturn(run func(context.Context) (int, error)) *LinkRepository_Count_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteByURL provides a mock function with given fields: ctx, url, chatID
func (_m *LinkRepository) DeleteByURL(ctx context.Context, url string, chatID int64) error {
	ret := _m.Called(ctx, url, chatID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteByURL")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int64) error); ok {
		r0 = rf(ctx, url, chatID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepository_DeleteByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteByURL'
type LinkRepository_DeleteByURL_Call struct {
	*mock.Call
}

// DeleteByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
//   - chatID int64
func (_e *LinkRepository_Expecter) DeleteByURL(ctx interface{}, url interface{}, chatID interface{}) *LinkRepository_DeleteByURL_Call {
	return &LinkRepository_DeleteByURL_Call{Call: _e.mock.On("DeleteByURL", ctx, url, chatID)}
}

func (_c *LinkRepository_DeleteByURL_Call) Run(run func(ctx context.Context, url string, chatID int64)) *LinkRepository_DeleteByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(int64))
	})
	return _c
}

func (_c *LinkRepository_DeleteByURL_Call) Return(_a0 error) *LinkRepository_DeleteByURL_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepository_DeleteByURL_Call) RunAndReturn(run func(context.Context, string, int64) error) *LinkRepository_DeleteByURL_Call {
	_c.Call.Return(run)
	return _c
}

// FindByChatID provides a mock function with given fields: ctx, chatID
func (_m *LinkRepository) FindByChatID(ctx context.Context, chatID int64) ([]*models.Link, error) {
	ret := _m.Called(ctx, chatID)

	if len(ret) == 0 {
		panic("no return value specified for FindByChatID")
	}

	var r0 []*models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]*models.Link, error)); ok {
		return rf(ctx, chatID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []*models.Link); ok {
		r0 = rf(ctx, chatID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, chatID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepository_FindByChatID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByChatID'
type LinkRepository_FindByChatID_Call struct {
	*mock.Call
}

// FindByChatID is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID int64
func (_e *LinkRepository_Expecter) FindByChatID(ctx interface{}, chatID interface{}) *LinkRepository_FindByChatID_Call {
	return &LinkRepository_FindByChatID_Call{Call: _e.mock.On("FindByChatID", ctx, chatID)}
}

func (_c *LinkRepository_FindByChatID_Call) Run(run func(ctx context.Context, chatID int64)) *LinkRepository_FindByChatID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *LinkRepository_FindByChatID_Call) Return(_a0 []*models.Link, _a1 error) *LinkRepository_FindByChatID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepository_FindByChatID_Call) RunAndReturn(run func(context.Context, int64) ([]*models.Link, error)) *LinkRepository_FindByChatID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByID provides a mock function with given fields: ctx, id
func (_m *LinkRepository) FindByID(ctx context.Context, id int64) (*models.Link, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for FindByID")
	}

	var r0 *models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Link, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Link); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepository_FindByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByID'
type LinkRepository_FindByID_Call struct {
	*mock.Call
}

// FindByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *LinkRepository_Expecter) FindByID(ctx interface{}, id interface{}) *LinkRepository_FindByID_Call {
	return &LinkRepository_FindByID_Call{Call: _e.mock.On("FindByID", ctx, id)}
}

func (_c *LinkRepository_FindByID_Call) Run(run func(ctx context.Context, id int64)) *LinkRepository_FindByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *LinkRepository_FindByID_Call) Return(_a0 *models.Link, _a1 error) *LinkRepository_FindByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepository_FindByID_Call) RunAndReturn(run func(context.Context, int64) (*models.Link, error)) *LinkRepository_FindByID_Call {
	_c.Call.Return(run)
	return _c
}

// FindByURL provides a mock function with given fields: ctx, url
func (_m *LinkRepository) FindByURL(ctx context.Context, url string) (*models.Link, error) {
	ret := _m.Called(ctx, url)

	if len(ret) == 0 {
		panic("no return value specified for FindByURL")
	}

	var r0 *models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Link, error)); ok {
		return rf(ctx, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Link); ok {
		r0 = rf(ctx, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepository_FindByURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByURL'
type LinkRepository_FindByURL_Call struct {
	*mock.Call
}

// FindByURL is a helper method to define mock.On call
//   - ctx context.Context
//   - url string
func (_e *LinkRepository_Expecter) FindByURL(ctx interface{}, url interface{}) *LinkRepository_FindByURL_Call {
	return &LinkRepository_FindByURL_Call{Call: _e.mock.On("FindByURL", ctx, url)}
}

func (_c *LinkRepository_FindByURL_Call) Run(run func(ctx context.Context, url string)) *LinkRepository_FindByURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *LinkRepository_FindByURL_Call) Return(_a0 *models.Link, _a1 error) *LinkRepository_FindByURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepository_FindByURL_Call) RunAndReturn(run func(context.Context, string) (*models.Link, error)) *LinkRepository_FindByURL_Call {
	_c.Call.Return(run)
	return _c
}

// FindDue provides a mock function with given fields: ctx, limit, offset
func (_m *LinkRepository) FindDue(ctx context.Context, limit int, offset int) ([]*models.Link, error) {
	ret := _m.Called(ctx, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for FindDue")
	}

	var r0 []*models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int, int) ([]*models.Link, error)); ok {
		return rf(ctx, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int, int) []*models.Link); ok {
		r0 = rf(ctx, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = rf(ctx, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepository_FindDue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindDue'
type LinkRepository_FindDue_Call struct {
	*mock.Call
}

// FindDue is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
func (_e *LinkRepository_Expecter) FindDue(ctx interface{}, limit interface{}, offset interface{}) *LinkRepository_FindDue_Call {
	return &LinkRepository_FindDue_Call{Call: _e.mock.On("FindDue", ctx, limit, offset)}
}

func (_c *LinkRepository_FindDue_Call) Run(run func(ctx context.Context, limit int, offset int)) *LinkRepository_FindDue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int), args[2].(int))
	})
	return _c
}

func (_c *LinkRepository_FindDue_Call) Return(_a0 []*models.Link, _a1 error) *LinkRepository_FindDue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepository_FindDue_Call) RunAndReturn(run func(context.Context, int, int) ([]*models.Link, error)) *LinkRepository_FindDue_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function with given fields: ctx
func (_m *LinkRepository) GetAll(ctx context.Context) ([]*models.Link, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []*models.Link
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*models.Link, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*models.Link); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Link)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LinkRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type LinkRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
func (_e *LinkRepository_Expecter) GetAll(ctx interface{}) *LinkRepository_GetAll_Call {
	return &LinkRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx)}
}

func (_c *LinkRepository_GetAll_Call) Run(run func(ctx context.Context)) *LinkRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *LinkRepository_GetAll_Call) Return(_a0 []*models.Link, _a1 error) *LinkRepository_GetAll_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *LinkRepository_GetAll_Call) RunAndReturn(run func(context.Context) ([]*models.Link, error)) *LinkRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, link
func (_m *LinkRepository) Save(ctx context.Context, link *models.Link) error {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Link) error); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type LinkRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - link *models.Link
func (_e *LinkRepository_Expecter) Save(ctx interface{}, link interface{}) *LinkRepository_Save_Call {
	return &LinkRepository_Save_Call{Call: _e.mock.On("Save", ctx, link)}
}

func (_c *LinkRepository_Save_Call) Run(run func(ctx context.Context, link *models.Link)) *LinkRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Link))
	})
	return _c
}

func (_c *LinkRepository_Save_Call) Return(_a0 error) *LinkRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepository_Save_Call) RunAndReturn(run func(context.Context, *models.Link) error) *LinkRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// SaveFilters provides a mock function with given fields: ctx, linkID, filters
func (_m *LinkRepository) SaveFilters(ctx context.Context, linkID int64, filters []string) error {
	ret := _m.Called(ctx, linkID, filters)

	if len(ret) == 0 {
		panic("no return value specified for SaveFilters")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []string) error); ok {
		r0 = rf(ctx, linkID, filters)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepository_SaveFilters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveFilters'
type LinkRepository_SaveFilters_Call struct {
	*mock.Call
}

// SaveFilters is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
//   - filters []string
func (_e *LinkRepository_Expecter) SaveFilters(ctx interface{}, linkID interface{}, filters interface{}) *LinkRepository_SaveFilters_Call {
	return &LinkRepository_SaveFilters_Call{Call: _e.mock.On("SaveFilters", ctx, linkID, filters)}
}

func (_c *LinkRepository_SaveFilters_Call) Run(run func(ctx context.Context, linkID int64, filters []string)) *LinkRepository_SaveFilters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]string))
	})
	return _c
}

func (_c *LinkRepository_SaveFilters_Call) Return(_a0 error) *LinkRepository_SaveFilters_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepository_SaveFilters_Call) RunAndReturn(run func(context.Context, int64, []string) error) *LinkRepository_SaveFilters_Call {
	_c.Call.Return(run)
	return _c
}

// SaveTags provides a mock function with given fields: ctx, linkID, tags
func (_m *LinkRepository) SaveTags(ctx context.Context, linkID int64, tags []string) error {
	ret := _m.Called(ctx, linkID, tags)

	if len(ret) == 0 {
		panic("no return value specified for SaveTags")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, []string) error); ok {
		r0 = rf(ctx, linkID, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepository_SaveTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveTags'
type LinkRepository_SaveTags_Call struct {
	*mock.Call
}

// SaveTags is a helper method to define mock.On call
//   - ctx context.Context
//   - linkID int64
//   - tags []string
func (_e *LinkRepository_Expecter) SaveTags(ctx interface{}, linkID interface{}, tags interface{}) *LinkRepository_SaveTags_Call {
	return &LinkRepository_SaveTags_Call{Call: _e.mock.On("SaveTags", ctx, linkID, tags)}
}

func (_c *LinkRepository_SaveTags_Call) Run(run func(ctx context.Context, linkID int64, tags []string)) *LinkRepository_SaveTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64), args[2].([]string))
	})
	return _c
}

func (_c *LinkRepository_SaveTags_Call) Return(_a0 error) *LinkRepository_SaveTags_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepository_SaveTags_Call) RunAndReturn(run func(context.Context, int64, []string) error) *LinkRepository_SaveTags_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, link
func (_m *LinkRepository) Update(ctx context.Context, link *models.Link) error {
	ret := _m.Called(ctx, link)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Link) error); ok {
		r0 = rf(ctx, link)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// LinkRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type LinkRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - link *models.Link
func (_e *LinkRepository_Expecter) Update(ctx interface{}, link interface{}) *LinkRepository_Update_Call {
	return &LinkRepository_Update_Call{Call: _e.mock.On("Update", ctx, link)}
}

func (_c *LinkRepository_Update_Call) Run(run func(ctx context.Context, link *models.Link)) *LinkRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Link))
	})
	return _c
}

func (_c *LinkRepository_Update_Call) Return(_a0 error) *LinkRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *LinkRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Link) error) *LinkRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewLinkRepository creates a new instance of LinkRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLinkRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *LinkRepository {
	mock := &LinkRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
