FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/bin/scrapper ./cmd/scrapper

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/bin/scrapper /app/bin/scrapper

COPY .env /app/

RUN apk --no-cache add ca-certificates

EXPOSE 8081

CMD ["/app/bin/scrapper"] 