FROM golang:1.23-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o /app/bin/bot ./cmd/bot

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/bin/bot /app/bin/bot

COPY .env /app/

RUN apk --no-cache add ca-certificates

EXPOSE 8080

CMD ["/app/bin/bot"] 