version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: "no"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - link_tracker_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    container_name: link_tracker_app
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    ports:
      - "${BOT_SERVER_PORT}:8080"
      - "${SCRAPPER_SERVER_PORT}:8081"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - BOT_BASE_URL=${BOT_BASE_URL}
      - SCRAPPER_BASE_URL=${SCRAPPER_BASE_URL}
      - SCHEDULER_CHECK_INTERVAL=${SCHEDULER_CHECK_INTERVAL}
      - USE_PARALLEL_SCHEDULER=${USE_PARALLEL_SCHEDULER}
      - DATABASE_ACCESS_TYPE=${DATABASE_ACCESS_TYPE}
      - DATABASE_BATCH_SIZE=${DATABASE_BATCH_SIZE}
      - DATABASE_MAX_CONNECTIONS=${DATABASE_MAX_CONNECTIONS}
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      - STACKOVERFLOW_API_TOKEN=${STACKOVERFLOW_API_TOKEN}
    networks:
      - link_tracker_network

  migrations:
    image: migrate/migrate
    container_name: link_tracker_migrations
    depends_on:
      postgres:
        condition: service_healthy
    command: ["-path", "/migrations", "-database", "${DATABASE_URL}", "up"]
    volumes:
      - ./migrations:/migrations
    networks:
      - link_tracker_network
    restart: on-failure

networks:
  link_tracker_network:
    driver: bridge

volumes:
  postgres_data: 