// Code generated by mockery v2.53.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// CheckUpdater is an autogenerated mock type for the CheckUpdater type
type CheckUpdater struct {
	mock.Mock
}

// CheckUpdates provides a mock function with given fields: ctx
func (_m *CheckUpdater) CheckUpdates(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CheckUpdates")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewCheckUpdater creates a new instance of CheckUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckUpdater {
	mock := &CheckUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
