// Code generated by ogen, DO NOT EDIT.

package v1_bot

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// UpdatesPost implements POST /updates operation.
//
// Отправить обновление.
//
// POST /updates
func (UnimplementedHandler) UpdatesPost(ctx context.Context, req *LinkUpdate) (r UpdatesPostRes, _ error) {
	return r, ht.ErrNotImplemented
}
