// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"
)

// QuestionUpdateGetter is an autogenerated mock type for the QuestionUpdateGetter type
type QuestionUpdateGetter struct {
	mock.Mock
}

// GetQuestionLastUpdate provides a mock function with given fields: ctx, questionID
func (_m *QuestionUpdateGetter) GetQuestionLastUpdate(ctx context.Context, questionID int64) (time.Time, error) {
	ret := _m.Called(ctx, questionID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionLastUpdate")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (time.Time, error)); ok {
		return rf(ctx, questionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) time.Time); ok {
		r0 = rf(ctx, questionID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, questionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewQuestionUpdateGetter creates a new instance of QuestionUpdateGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewQuestionUpdateGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *QuestionUpdateGetter {
	mock := &QuestionUpdateGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
