// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	models "github.com/central-university-dev/go-Matthew11K/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// StackOverflowClient is an autogenerated mock type for the StackOverflowClient type
type StackOverflowClient struct {
	mock.Mock
}

type StackOverflowClient_Expecter struct {
	mock *mock.Mock
}

func (_m *StackOverflowClient) EXPECT() *StackOverflowClient_Expecter {
	return &StackOverflowClient_Expecter{mock: &_m.Mock}
}

// GetQuestionDetails provides a mock function with given fields: ctx, questionID
func (_m *StackOverflowClient) GetQuestionDetails(ctx context.Context, questionID int64) (*models.StackOverflowDetails, error) {
	ret := _m.Called(ctx, questionID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionDetails")
	}

	var r0 *models.StackOverflowDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.StackOverflowDetails, error)); ok {
		return rf(ctx, questionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.StackOverflowDetails); ok {
		r0 = rf(ctx, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.StackOverflowDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, questionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StackOverflowClient_GetQuestionDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionDetails'
type StackOverflowClient_GetQuestionDetails_Call struct {
	*mock.Call
}

// GetQuestionDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - questionID int64
func (_e *StackOverflowClient_Expecter) GetQuestionDetails(ctx interface{}, questionID interface{}) *StackOverflowClient_GetQuestionDetails_Call {
	return &StackOverflowClient_GetQuestionDetails_Call{Call: _e.mock.On("GetQuestionDetails", ctx, questionID)}
}

func (_c *StackOverflowClient_GetQuestionDetails_Call) Run(run func(ctx context.Context, questionID int64)) *StackOverflowClient_GetQuestionDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *StackOverflowClient_GetQuestionDetails_Call) Return(_a0 *models.StackOverflowDetails, _a1 error) *StackOverflowClient_GetQuestionDetails_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StackOverflowClient_GetQuestionDetails_Call) RunAndReturn(run func(context.Context, int64) (*models.StackOverflowDetails, error)) *StackOverflowClient_GetQuestionDetails_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuestionLastUpdate provides a mock function with given fields: ctx, questionID
func (_m *StackOverflowClient) GetQuestionLastUpdate(ctx context.Context, questionID int64) (time.Time, error) {
	ret := _m.Called(ctx, questionID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionLastUpdate")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (time.Time, error)); ok {
		return rf(ctx, questionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) time.Time); ok {
		r0 = rf(ctx, questionID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, questionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StackOverflowClient_GetQuestionLastUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuestionLastUpdate'
type StackOverflowClient_GetQuestionLastUpdate_Call struct {
	*mock.Call
}

// GetQuestionLastUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - questionID int64
func (_e *StackOverflowClient_Expecter) GetQuestionLastUpdate(ctx interface{}, questionID interface{}) *StackOverflowClient_GetQuestionLastUpdate_Call {
	return &StackOverflowClient_GetQuestionLastUpdate_Call{Call: _e.mock.On("GetQuestionLastUpdate", ctx, questionID)}
}

func (_c *StackOverflowClient_GetQuestionLastUpdate_Call) Run(run func(ctx context.Context, questionID int64)) *StackOverflowClient_GetQuestionLastUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *StackOverflowClient_GetQuestionLastUpdate_Call) Return(_a0 time.Time, _a1 error) *StackOverflowClient_GetQuestionLastUpdate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *StackOverflowClient_GetQuestionLastUpdate_Call) RunAndReturn(run func(context.Context, int64) (time.Time, error)) *StackOverflowClient_GetQuestionLastUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// NewStackOverflowClient creates a new instance of StackOverflowClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStackOverflowClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *StackOverflowClient {
	mock := &StackOverflowClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
