// Code generated by ogen, DO NOT EDIT.
package v1_scrapper

type LinksDeleteRes interface {
	linksDeleteRes()
}

type LinksGetRes interface {
	linksGetRes()
}

type LinksPostRes interface {
	linksPostRes()
}

type NotificationSettingsPostRes interface {
	notificationSettingsPostRes()
}

type TgChatIDDeleteRes interface {
	tgChatIDDeleteRes()
}

type TgChatIDPostRes interface {
	tgChatIDPostRes()
}
