// Code generated by ogen, DO NOT EDIT.

package v1_scrapper

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// DigestGet implements GET /digest operation.
//
// Получить дайджест обновлений ссылок.
//
// GET /digest
func (UnimplementedHandler) DigestGet(ctx context.Context, params DigestGetParams) (r DigestGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LinksDelete implements DELETE /links operation.
//
// Убрать отслеживание ссылки.
//
// DELETE /links
func (UnimplementedHandler) LinksDelete(ctx context.Context, req *RemoveLinkRequest, params LinksDeleteParams) (r LinksDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LinksGet implements GET /links operation.
//
// Получить все отслеживаемые ссылки.
//
// GET /links
func (UnimplementedHandler) LinksGet(ctx context.Context, params LinksGetParams) (r LinksGetRes, _ error) {
	return r, ht.ErrNotImplemented
}

// LinksPost implements POST /links operation.
//
// Добавить отслеживание ссылки.
//
// POST /links
func (UnimplementedHandler) LinksPost(ctx context.Context, req *AddLinkRequest, params LinksPostParams) (r LinksPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TgChatIDDelete implements DELETE /tg-chat/{id} operation.
//
// Удалить чат.
//
// DELETE /tg-chat/{id}
func (UnimplementedHandler) TgChatIDDelete(ctx context.Context, params TgChatIDDeleteParams) (r TgChatIDDeleteRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TgChatIDPost implements POST /tg-chat/{id} operation.
//
// Зарегистрировать чат.
//
// POST /tg-chat/{id}
func (UnimplementedHandler) TgChatIDPost(ctx context.Context, req OptChatSettings, params TgChatIDPostParams) (r TgChatIDPostRes, _ error) {
	return r, ht.ErrNotImplemented
}

// TgChatIDPut implements PUT /tg-chat/{id} operation.
//
// Обновить настройки чата.
//
// PUT /tg-chat/{id}
func (UnimplementedHandler) TgChatIDPut(ctx context.Context, req *ChatSettings, params TgChatIDPutParams) (r TgChatIDPutRes, _ error) {
	return r, ht.ErrNotImplemented
}
