// Code generated by ogen, DO NOT EDIT.

package v1_scrapper

import (
	"github.com/go-faster/jx"

	"github.com/ogen-go/ogen/json"
)

// setDefaults set default value of fields.
func (s *ChatSettings) setDefaults() {
	{
		val := ChatSettingsNotificationMode("instant")
		s.NotificationMode.SetTo(val)
	}
	{
		val, _ := json.DecodeTime(jx.DecodeStr("\"10:00:00\""))
		s.DigestTime.SetTo(val)
	}
}
