// Code generated by ogen, DO NOT EDIT.

package v1_scrapper

// OperationName is the ogen operation name
type OperationName = string

const (
	DigestGetOperation      OperationName = "DigestGet"
	LinksDeleteOperation    OperationName = "LinksDelete"
	LinksGetOperation       OperationName = "LinksGet"
	LinksPostOperation      OperationName = "LinksPost"
	TgChatIDDeleteOperation OperationName = "TgChatIDDelete"
	TgChatIDPostOperation   OperationName = "TgChatIDPost"
	TgChatIDPutOperation    OperationName = "TgChatIDPut"
)
