// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import (
	context "context"

	models "github.com/central-university-dev/go-Matthew11K/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// DigestUpdater is an autogenerated mock type for the DigestUpdater type
type DigestUpdater struct {
	mock.Mock
}

// AddUpdate provides a mock function with given fields: ctx, update
func (_m *DigestUpdater) AddUpdate(ctx context.Context, update *models.LinkUpdate) error {
	ret := _m.Called(ctx, update)

	if len(ret) == 0 {
		panic("no return value specified for AddUpdate")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.LinkUpdate) error); ok {
		r0 = rf(ctx, update)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewDigestUpdater creates a new instance of DigestUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDigestUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *DigestUpdater {
	mock := &DigestUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
