// Code generated by mockery v2.53.2. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	models "github.com/central-university-dev/go-Matthew11K/internal/domain/models"
	mock "github.com/stretchr/testify/mock"
)

// StackOverflowClient is an autogenerated mock type for the StackOverflowClient type
type StackOverflowClient struct {
	mock.Mock
}

// GetQuestionDetails provides a mock function with given fields: ctx, questionID
func (_m *StackOverflowClient) GetQuestionDetails(ctx context.Context, questionID int64) (*models.ContentDetails, error) {
	ret := _m.Called(ctx, questionID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionDetails")
	}

	var r0 *models.ContentDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.ContentDetails, error)); ok {
		return rf(ctx, questionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.ContentDetails); ok {
		r0 = rf(ctx, questionID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ContentDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, questionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetQuestionLastUpdate provides a mock function with given fields: ctx, questionID
func (_m *StackOverflowClient) GetQuestionLastUpdate(ctx context.Context, questionID int64) (time.Time, error) {
	ret := _m.Called(ctx, questionID)

	if len(ret) == 0 {
		panic("no return value specified for GetQuestionLastUpdate")
	}

	var r0 time.Time
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (time.Time, error)); ok {
		return rf(ctx, questionID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) time.Time); ok {
		r0 = rf(ctx, questionID)
	} else {
		r0 = ret.Get(0).(time.Time)
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, questionID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewStackOverflowClient creates a new instance of StackOverflowClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStackOverflowClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *StackOverflowClient {
	mock := &StackOverflowClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
